/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ZenButton {
        "accent": boolean;
        "disabled": boolean;
        "primary": boolean;
        "size": string;
    }
}
declare global {
    interface HTMLZenButtonElement extends Components.ZenButton, HTMLStencilElement {
    }
    var HTMLZenButtonElement: {
        prototype: HTMLZenButtonElement;
        new (): HTMLZenButtonElement;
    };
    interface HTMLElementTagNameMap {
        "zen-button": HTMLZenButtonElement;
    }
}
declare namespace LocalJSX {
    interface ZenButton {
        "accent"?: boolean;
        "disabled"?: boolean;
        "primary"?: boolean;
        "size"?: string;
    }
    interface IntrinsicElements {
        "zen-button": ZenButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "zen-button": LocalJSX.ZenButton & JSXBase.HTMLAttributes<HTMLZenButtonElement>;
        }
    }
}
